export const Images = [
  {
    id: 0,
    width: "null",
    height: "null",
    imageWidth: "350",
    imageHeight: "350",
    image: "/static/image/partener/r.png",
  },
  {
    id: 1,
    width: "width",
    height: "height",
    imageWidth: "350",
    imageHeight: "350",
    image: `/static/images/partener/logo_mairie_bordeaux_1.png`,
  },
  {
    id: 2,
    width: "width",
    height: "height",
    imageWidth: "350",
    imageHeight: "350",
    image: `/static/images/partener/logo_merignac.png`,
  },
  {
    id: 3,
    width: "width",
    height: "height",
    imageWidth: "350",
    imageHeight: "350",
    image: `/static/images/partener/logo_bruges.jpg`,
  },
  {
    id: 4,
    width: "width",
    height: "height",
    imageWidth: "350",
    imageHeight: "350",
    image: `/static/images/partener/logo-resize.png`,
  },
  {
    id: 5,
    width: "width",
    height: "height",
    imageWidth: "350",
    imageHeight: "350",
    image: `/static/images/partener/logo_bas.png`,
  },
  {
    id: 6,
    width: "width",
    height: "height",
    imageWidth: "350",
    imageHeight: "350",
    image: `/static/images/partener/logo_bouliac.jpg`,
  },

  {
    id: 8,
    width: "width",
    height: "height",
    imageWidth: "350",
    imageHeight: "350",
    image: `/static/images/partener/logo_lege_cap_ferret.jpg`,
  },
  {
    id: 9,
    width: "width",
    height: "height",
    imageWidth: "350",
    imageHeight: "350",
    image: `/static/images/partener/logo-footer.png`,
  },
];
