export type Content = {
  content: {
    mail: string;
    Title: string;
    adress: any;
    number: string;
    mapsLink: string;
    MoneyText: any;
    introText: any;
    MoneyTitle: string;
    introTitle: string;
    linkadress: string;
    offerTitle: string;
    socialText: any;
    youtubeVideoLink: string;
    youtubeTitle: string;
    socialTitle: string;
    usagesTitle: string;
    collectTitle: string;
    compostTitle: string;
    contactTitle: string;
    restaurantTitle: string;
    restaurantCollective: string;
    collectivites: string;
    particular: string;
    ourEngagement: string;
    environementTitle: string;
    CooperationTitle: string;
    CooperationText: any;
    sensibilisationTitle: string;
    collectText: any;
    sensibilisationText: any;
    environement: any;
    compostText: any;
  };
};
